name:       categorical
version:    0.1.0.0
synopsis:   Compiling to categories
author:     John Wiegley
maintainer: johnw@newartisans.com
license:    MIT
github:     jwiegley/categorical
category:   System

dependencies:
  - base        >= 4.9 && < 4.10
  - base-orphans
  - concat
  - containers
  - free
  - ghc-prim
  - newtype
  - semiring-simple
  - mtl         >= 2.2.1
  - profunctors >= 5.2 && < 5.3
  - transformers
  - z3
  - z3cat

library:
  source-dirs: src
  exposed-modules:
    - Categorical.AST
    - Categorical.Gather
    - Categorical.NonDet
    - Categorical.Program
    - Categorical.Template

tests:
  categorical:
    main: Main.hs
    source-dirs: test
    dependencies:
      - hspec == 2.*
      - categorical
      - quickcheck-io
